### ISSUE TITLE
Block Reinstall

### ISSUE THREAD

**Issue by IGS-GIT** [jbara2002/edge-remover#21]
Are there plans to add a registry rewrite to the script? Edge gets added back after every major update so it would be nice to have this completely block it.

**Comment by seba2282** [comment]
@jbara2002 You didn't added to version 2.6 ? I remember, you told how you added and you gave in that changelog informations about added key reg to scripts.

**Comment by jbara2002** [comment]
Yes. It added an policy but it doesn't apply to updating every major version of Windows. Microsoft Edge (Chromium and UWP) are included into Winodws CBS (Component Base System, infos located in `C:\Winodws\System32\CatRoot`). The package name is Microsoft-Windows-Internet-Browser-Package~~windows buld version. So in a nutshell , Microsoft Edge is included in the system install image and every time when you upgrade the OS , Microsoft Edge will be re-added. Apply the script again and the browser will gone until you reinstall of upgrade to major version of Windows.

**Comment by seba2282** [comment]
@jbara2002 so with full respect, why then are that all registry policy about don't update edge. 
I think time more interesting about how block that as user rule. Maybe old key reg don't work. And edge policies too. But i think it is something about block something more, bc by Windows update shouldn't download edge, when is upgrade version by wu. You don't think?

**Comment by jbara2002** [comment]
is upgrade version by wu is same to thing like to upgrade from an iso file, but is applied silently. So it not a policy to apply for upgrades. When something appears, will be implemented. but for now, is not possible because in the downloaded image it includes edge and it integrates (will not install).

**Comment by seba2282** [comment]
But from Iso you have full. Via WU you have part because that updates if regular update, you have smaller with new functions. I thought it let's then stay still how user made in settings, etc. But reset fabric settings, will on 100% put all. So i don't know. I can observe on virtual machine example how will be with windows 11, because there i putted out edge and replaced by Firefox. Maybe someone find method to block install edge via WU updates too finally someday.
